### ISSUE TITLE
Periodic full page reloads in Firefox

### ISSUE THREAD

**Issue by pygy** [porsager/flems.io#17]
Open https://flems.io in Firefox and start editing. After a few seconds, the page will reload, and reload, and reload, making Flems almost unusable.

**Comment by porsager** [comment]
Is there a chance you have an old version version cached? (I'm not able to reproduce).

I made some changes a few weeks back to fix an issue with flems filling up the global browser history. I changed from `history.replaceState` to `location.hash =`. I also had a reload in `onhashchange` which is needed because safari reuses flems windows, so I need to reload on hashchange there (only way to know if someone clicked a flems link)). For a couple of days there was an issue with the hashchange triggering reloads (i mistakenly thought it was synchronous), but I should think I fixed it back then :)

**Comment by fuzetsu** [comment]
This issue still seems to be occurring for me.  I made sure to completely clear the cache.

That `location.reload()` in the `hashchange` even you mention for safari seems to be triggering randomly on firefox. 

Some sort of timing issue where setting the hash takes long enough that the `setTimeout` fires before the `hashchange` event?

**Comment by fuzetsu** [comment]
Seems to happen most often when clicking to move the cursor.

It makes flems fairly hard to use in firefox because the full page refresh blows away the undo stack. 
The back button mostly works as a workaround, but not ideal.

![ezgif-1-393f59221052](https://user-images.githubusercontent.com/848652/66169862-d725fe00-e60f-11e9-8f09-6971886d1aa2.gif)

**Comment by porsager** [comment]
Sorry @fuzetsu for the late reply.. That's pretty horrible :-/ I'll take a closer look during the weekend.

**Comment by porsager** [comment]
Actually looking at it now.. I can repro here...

**Comment by porsager** [comment]
Should be good now ;) Silly race condition in firefox. Don't feel like debugging it further, but raising the timeout from 0 to 5ms fixes the issue.

**Comment by porsager** [comment]
Can you check if you can repro now?

**Comment by fuzetsu** [comment]
That seems to have fixed it, can't repro anymore :tada:

**Comment by fuzetsu** [comment]
Thank you!

**Comment by porsager** [comment]
Great :) I can still make it happen on tab change with big files, so I'll leave the issue open until I can look closer..

**Comment by fuzetsu** [comment]
Sounds good! It happening less often for now is a relief.

Switched to firefox as my primary browser recently but had to keep opening up chrome for flems :cry:

**Comment by porsager** [comment]
Hehe.. Courageous :D How's it working out? (I use chrome for dev, and safari for daily browsing).

I've disabled onhashchange handling completely for Firefox now, so the issue should be completely gone. It was only there to ensure Safari worked properly so no reason to have it for Firefox.

**Comment by fuzetsu** [comment]
Heh! Good so far. Made me notice a couple of Firefox compatibility bugs in one of my userscripts. 

Don't miss anything about chrome yet, except for devtools a bit, Firefox's devtools are good and fairly similar, but it's taking a little bit of time to get used to it.

> I've disabled onhashchange handling completely for Firefox now, so the issue should be completely gone. It was only there to ensure Safari worked properly so no reason to have it for Firefox.

Perfect :+1: sounds reasonable.
